In [1]:
import pandas as pd
import numpy as np  
import matplotlib.pyplot as plt

In [3]:

matrix = np.array([[1, 0.48, 1.52, 0.71],
                   [2.05, 1, 3.26, 1.56],
                   [0.64, 0.3, 1, 0.46],
                   [1.41, 0.61, 2.08, 1]])

print(matrix)

[[1.   0.48 1.52 0.71]
 [2.05 1.   3.26 1.56]
 [0.64 0.3  1.   0.46]
 [1.41 0.61 2.08 1.  ]]


In [4]:
# point-wise multiplication of 2 matrices
def multiply(matrix1, matrix2):
    return matrix1 * matrix2

a = matrix

interchange = multiply(a, a.T)


In [5]:
print(interchange)

[[1.     0.984  0.9728 1.0011]
 [0.984  1.     0.978  0.9516]
 [0.9728 0.978  1.     0.9568]
 [1.0011 0.9516 0.9568 1.    ]]


In [12]:
import numpy as np

# Original matrix
original_matrix = np.array([[1.0, 0.48, 1.52, 0.71],
                            [2.05, 1.0, 3.26, 1.56],
                            [0.64, 0.3, 1.0, 0.46],
                            [1.41, 0.61, 2.08, 1.0]])

# Matrix with 1/x elements
result_matrix = 1 / original_matrix

print(result_matrix.T)
print(matrix)
print(result_matrix.T - matrix)

[[1.         0.48780488 1.5625     0.70921986]
 [2.08333333 1.         3.33333333 1.63934426]
 [0.65789474 0.30674847 1.         0.48076923]
 [1.4084507  0.64102564 2.17391304 1.        ]]
[[1.   0.48 1.52 0.71]
 [2.05 1.   3.26 1.56]
 [0.64 0.3  1.   0.46]
 [1.41 0.61 2.08 1.  ]]
[[ 0.          0.00780488  0.0425     -0.00078014]
 [ 0.03333333  0.          0.07333333  0.07934426]
 [ 0.01789474  0.00674847  0.          0.02076923]
 [-0.0015493   0.03102564  0.09391304  0.        ]]


In [6]:
# rotate the matrix

# left shift the matrix:
def rotate(matrix):
    return np.roll(matrix, 1, axis=1)

rot = rotate(matrix)
print(rot)


[[0.71 1.   0.48 1.52]
 [1.56 2.05 1.   3.26]
 [0.46 0.64 0.3  1.  ]
 [1.   1.41 0.61 2.08]]


In [ ]:
matrix[3][1]

In [16]:
## Write all possible 4 digit numbers using 0, 1, 2, 3 with repitition allowed:

digits = [0, 1, 2, 3]
numbers = []
max = 0

for d1 in digits:
    for d2 in digits:
        for d3 in digits:
            for d4 in digits:
                score = matrix[3][d1] * matrix[d1][d2] * matrix[d2][d3] * matrix[d3][d4] * matrix[d4][3]
                if score > max:
                    max = score
                    numbers = [d1, d2, d3, d4]
                    print("max:" ,numbers, max)
                if(score > 1.05):
                        print(score, d1, d2, d3, d4, max)



max: [0, 0, 0, 0] 1.0010999999999999
max: [0, 0, 0, 1] 1.055808
1.055808 0 0 0 1 1.055808
1.055808 0 0 1 1 1.055808
1.055808 0 0 1 3 1.055808
1.055808 0 1 1 1 1.055808
1.055808 0 1 1 3 1.055808
max: [0, 1, 3, 0] 1.0569693888
1.0569693888 0 1 3 0 1.0569693888
1.055808 0 1 3 3 1.0569693888
1.0569693887999998 0 3 0 1 1.0569693888
1.055808 3 0 0 1 1.0569693888
1.055808 3 0 1 1 1.0569693888
1.055808 3 0 1 3 1.0569693888
1.055808 3 3 0 1 1.0569693888


In [ ]:
tower_values = [10, 20, 30, 40, 50]  # Example tower values

# Step 1: Calculate the sum of all tower values
total_sum = sum(tower_values)

# Step 2 and 3: Assign weights based on magnitude
weights = [value / total_sum * 100 for value in tower_values]

# Step 4: Normalize the weights
total_weight = sum(weights)
weights = [weight / total_weight * 100 for weight in weights]

print(weights)


In [3]:
for i in range(1, 10):
    print(i)

1
2
3
4
5
6
7
8
9
